### ISSUE TITLE
Recipe book icon not displaying correctly with center-crosshair

### ISSUE THREAD

**Issue by RiftBladeMc** [bradleyq/shader-toolkit#3]
When using center-crosshair the recipe book icon in the survival mode inventory does not display correctly.

Here is how it looks with center-crosshair:

![with-center-crosshair](https://user-images.githubusercontent.com/41810843/235259479-6fec37ca-3032-47a0-8150-7835ec10187c.png)

Here is how it is supposed to look:

![without-center-crosshair](https://user-images.githubusercontent.com/41810843/235259506-23f46d2e-5db8-4ec4-9acf-5ead9b7e988f.png)

**Comment by bradleyq** [comment]
should be fixed.
